[package]
name = "find-crate"
version = "0.4.0"
authors = ["Taiki Endo <te316e89@gmail.com>"]
edition = "2018"
license = "Apache-2.0/MIT"
repository = "https://github.com/taiki-e/find-crate"
documentation = "https://docs.rs/find-crate/"
keywords = ["macros", "crate"]
categories = ["development-tools::procedural-macro-helpers"]
readme = "README.md"
description = """
Find the crate name from the current Cargo.toml.
"""

[dependencies]
toml = "0.5.3"

[dev-dependencies]
proc-macro2 = "1.0"
quote = "1.0"
semver = "0.9"
