[package]
name = "find-crate"
# NB: When modifying, also modify html_root_url in lib.rs
version = "0.4.0"
authors = ["Taiki Endo <te316e89@gmail.com>"]
edition = "2018"
license = "Apache-2.0/MIT"
description = "Find the crate name from the current Cargo.toml ($crate for proc-macro)."
repository = "https://github.com/taiki-e/find-crate"
documentation = "https://docs.rs/find-crate/"
readme = "README.md"
keywords = ["macros", "crate"]
categories = ["development-tools::procedural-macro-helpers"]

[dependencies]
serde = ">=1.0.7, <2"
toml = "0.5.0" # https://github.com/rust-lang/cargo/blob/master/Cargo.toml

[dev-dependencies]
proc-macro2 = "0.4.13"
quote = "0.6.8"
